
spring.application.name=banking

# --- Flyway ---
spring.flyway.enabled=true

# --- Datasource ---
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.username=${DB_USERNAME:hau}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Security ---
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:3600000}

# --- Bootstrap admin ---
bootstrap.admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:false}
bootstrap.admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}

