
spring.application.name=banking
spring.flyway.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=hau
spring.datasource.password=abc123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=lADXuUrUCgcODA0SI+qmjUDlJZ00hMmzWrE3Fui04Yk
security.jwt.expiration=3600000

bootstrap.admin.email=${BOOTSTRAP_ADMIN_EMAIL:}
bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
bootstrap.admin.enabled=true

